### ISSUE TITLE
Mesh Normalisation to original coordinate space

### ISSUE THREAD

**Issue by sainatarajan** [ai-med/Vox2Cortex#1]
Hi all,

Thanks for this wonderful repo. I have a doubt since you seem to be using pytorch3d.

When training your model, do you normalise your meshes to be in the space [-1, 1] and then transform to original space using scaling and translation after you get model's output mesh or do you directly train your model so that the coordinates of your output Mesh from model are in their original space?

Thanks!

**Comment by fabibo3** [comment]
Hi Sai,

Thanks for your interest in the repo. We train the model in the normalized space and transform the meshes back to the original space after the prediction has been completed.

Best regards,
Fabi
