### ISSUE TITLE
weights for segmentations?

### ISSUE THREAD

**Issue by huilinyang** [ai-med/Vox2Cortex#10]
Hello, I noticed that there are three (because of deep supervision) final output maps for segmentation? Could you please post the weights you used for the three segmentations for the loss? And why the N_V_CLASSES (the number of vertex classes to distinguish) is 2? Why should it including background? Thanks a lot!

**Comment by fabibo3** [comment]
Hi, the losses of the three segmentation outputs are simply added, i.e., weights of one. 

The parameter N_V_CLASSES defines the number of voxel classes, not vertex classes. This seems to be a typo in the description of parameters which I just fixed.
