### ISSUE TITLE
About figure3 in the paper

### ISSUE THREAD

**Issue by Orbis36** [ai-med/Vox2Cortex#11]
Hi,
Thanks for your work first.
I wanna know what is the meaning of "NNs, ID" in the figure.
In line 342 of graph_net.py, "new_meshes.move_verts(deltaV_padded)", it seems after updating the location of meshes, the next block will use the new location to calculate. So in this way I'm confused about the meaning of "NNs, ID", and there is no explanation in the paper as well(I apologize if I missed anything).

Looking forward to your reply.

**Comment by fabibo3** [comment]
Hi, the meaning is the following:

- NNs = the positions of the nearest-neighbor vertices from the respective other surface, i.e., from the outer surface for an inner surface's vertex and vice versa
- ID = an ID (0 or 1) that identifies the surface a vertex belongs to 

This information is concatenated with the vertex features before each deformation block. 

Hope this helps,
Best,
Fabi

**Comment by Orbis36** [comment]
Thanks so much, that solved my question.
