### ISSUE TITLE
How to exactly perform inference with more vertices with the model trained with fewer vertices?

### ISSUE THREAD

**Issue by huilinyang** [ai-med/Vox2Cortex#13]
Hi, could you please describe the steps/method you used to perform inference of high resolution (about 160000 vertices for each template) with the model trained on the lower resolution (about 40000 vertices for each template)? 

Thanks a lot!!!

**Comment by fabibo3** [comment]
Hi, just set the parameter `N_TEMPLATE_VERTICES` in `main.py` to 168058 after training.
