### ISSUE TITLE
Chamfer distance parameters

### ISSUE THREAD

**Issue by reitxel** [ai-med/Vox2Cortex#15]
Hi, I wanted to use the chamfer curvature loss in some experiments. I was wondering if you could upload the version of pytorch3d.loss.chamfer_distance you were using. I may be missing something, but I am not sure how to interpret the points_weights parameter. I tried modifying the source code of the function, but I wanted to be sure on the implementation. Thanks in advance!

**Comment by fabibo3** [comment]
Hi, it's implemented here: [https://github.com/fabibo3/pytorch3d](https://github.com/fabibo3/pytorch3d).
