### ISSUE TITLE
Evaluation resolutions? Whether the dice is calculated in the preprocessed space or in the original resolution?

### ISSUE THREAD

**Issue by MarsVillage** [ai-med/Vox2Cortex#16]
Hello,

Thank you for sharing your great work! As for the UNetFlow, how did you calculate the dice and ASSD? Were they calculated in the preprocessed resolution or converted to the original resolution and calculated?

Thank you so much!

**Comment by fabibo3** [comment]
Hi, the evaluation was done on the preprocessed data.
