### ISSUE TITLE
Cannot find the executables 'reg_aladin' and 'reg_resample' in the abdomen preprocessing folder

### ISSUE THREAD

**Issue by huilinyang** [ai-med/Vox2Cortex#17]
Hello,

Thank you so much for sharing this amazing work. When I tried to use the code to preprocess that abdomen data, it could not find the executables 'reg_aladin' and 'reg_resample' in the "preprocessing/abdomen/" folder. I wonder will you share these files? Your help will be greatly appreciated.

Thanks

**Comment by fabibo3** [comment]
These executables are part of niftyreg, please refer to http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftyReg.
