### ISSUE TITLE
supplementary templates missing

### ISSUE THREAD

**Issue by WilliamAshbee** [ai-med/Vox2Cortex#2]
the code references some templates that haven't been uploaded. could you check that all supplementary materials are uploaded. 
Great paper btw. 
Thanks. 
'../supplementary_material/white_pial/cortex_4_1000_3_smoothed_42016_sps[192, 208, 192]_ps[128, 144, 128].obj'
not in github

**Comment by fabibo3** [comment]
Hi William, thanks for the remark. This was just a naming issue and should be fixed now. Besides, I also added the larger template (with more vertices). Best, Fabi
