### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by huilinyang** [ai-med/Vox2Cortex#5]
Hello, how long did it takes to converge when you were training the final model?

**Comment by fabibo3** [comment]
Hi, training typically takes ~3 days on an Nvidia quadro P6000.

**Comment by huilinyang** [comment]
Thank you for your reply. Why did you use a batch size of 1? Have you tried other batch sizes? And whether all of the ground truth obtained from Freesurfer share the same number of vertexes, or vary among the dataset.

**Comment by fabibo3** [comment]
The batch size was limited by GPU memory in our experiments, I haven't tried larger batch sizes when working with all four surfaces.

The FreeSurfer surfaces can have different numbers of vertices, just make sure you set the parameter 'N_REF_POINTS_PER_STRUCTURE' to the min. number of vertices in your training set (per surface).

**Comment by huilinyang** [comment]
Thanks a lot. Specifically, could I know how many epochs did it need to converge when training? And how long for each epoch?

**Comment by fabibo3** [comment]
In the experiments described in the paper we trained for 40 epochs on ADNI and for 100 epochs on OASIS but we found later that training for a bit longer can further improve performance. The time required per epoch depends on the dataset size.
