### ISSUE TITLE
No 'ChamferAndNormalsAndCurvatureLoss'

### ISSUE THREAD

**Issue by huilinyang** [ai-med/Vox2Cortex#9]
Hello, I can't found the code of "ChamferAndNormalsAndCurvatureLoss", could you upload it? Thanks a lot!

**Comment by fabibo3** [comment]
This was a relic from some earlier experiments, the loss doesn't exist anymore. I removed its occurrence in train.py in https://github.com/ai-med/Vox2Cortex/commit/dbbcf4d5b308d5c8d843b85924988771a5a847cc .
